# Numpy

- NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers. 
- NumPy arrays are like Python’s built-in list type, 
    - they provide much more efficient storage and data operations as the arrays grow larger in size. 
- NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python


In [181]:
import numpy as np

# The NumPy ndarray: A Multidimensional Array Object
- N-dimensional array object, or ndarray, which is a fast, flexible container for large data sets 
- Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax
- An ndarray is a generic multidimensional container for homogeneous data
  - all of the elements must be the same type. 
  - Shape, a tuple indicating the size of each dimension, 
  - dtype, an object describing the data type of the array

## Creating ndarrays
- the ***array*** function accepts any sequence-like object (including other arrays) and produces a new NumPy array containing the passed data


In [182]:
data1 = [1, 3, 5, 7, 9, 11]

In [183]:
data1

[1, 3, 5, 7, 9, 11]

In [184]:
arr1 = np.array(data1)

In [185]:
arr1

array([ 1,  3,  5,  7,  9, 11])

In [186]:
arr1.ndim

1

In [187]:
data2 = [1, 3.7, 5, 7, 9, 11.4]

In [188]:
data2

[1, 3.7, 5, 7, 9, 11.4]

In [189]:
arr2 = np.array(data2)

In [190]:
arr2

array([ 1. ,  3.7,  5. ,  7. ,  9. , 11.4])

In [191]:
for x in arr2:
  print(x)

1.0
3.7
5.0
7.0
9.0
11.4


In [192]:
arr2 * 100

array([ 100.,  370.,  500.,  700.,  900., 1140.])

In [193]:
arrSbaglia = np.array([1, 2])

In [194]:
arr1

array([ 1,  3,  5,  7,  9, 11])

In [195]:
# arr1 + arrSbaglia

In [196]:
arr2 + arr1

array([ 2. ,  6.7, 10. , 14. , 18. , 22.4])

In [197]:
arr2.ndim

1

In [198]:
arr2.shape

(6,)

In [199]:
data_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [200]:
data_2[1][0]

4

In [201]:
data_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [202]:
arr_2 = np.array(data_2)

In [203]:
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [204]:
arr_2.ndim

2

In [205]:
arr_2.shape

(3, 3)

In [206]:
arr_3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [207]:
arr_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [208]:
arr_3.shape

(2, 2, 2)

In [209]:
arr_3.ndim

3

In [210]:
arr_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

- Other techniques for initializing ndarrays
  - ones
  - zeros
  - empty
  - eye

In [211]:
np.ones(16)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [212]:
np.ones((16,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [213]:
np.empty((3, 4))

array([[1.31242946e-316, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.14587773e-312, 1.03977794e-312, 1.23075756e-312,
        1.03977794e-312],
       [1.08221785e-312, 9.76118064e-313, 1.18831764e-312,
        1.90979621e-312]])

In [214]:
np.empty((3, 2, 3, 5, 6, 7, 8))

array([[[[[[[6.90152729e-310, 1.27264828e-316, 0.00000000e+000, ...,
             0.00000000e+000, 1.35717430e+131, 4.49543900e-086],
            [3.50819885e-033, 5.53287452e-048, 8.60392064e-067, ...,
             1.03896638e-095, 1.81148473e-152, 6.01347002e-154],
            [1.39736850e-076, 1.21089429e-099, 2.91000705e-033, ...,
             2.00291772e-076, 1.03080495e+136, 6.01347002e-154],
            ...,
            [6.01347002e-154, 1.68931646e-052, 5.20270271e-090, ...,
             4.44895249e-086, 6.00458990e-067, 1.03080551e+136],
            [6.01347002e-154, 3.69095140e-086, 8.60827304e-067, ...,
             1.05133697e-153, 1.12948092e-042, 8.52794449e-096],
            [1.81148473e-152, 6.01347002e-154, 1.57009846e-076, ...,
             2.62459657e+179, 4.44895249e-086, 6.00458990e-067]],

           [[1.03080551e+136, 6.01347002e-154, 3.03426177e-086, ...,
             2.00392844e-076, 9.46062935e-096, 3.93707082e-062],
            [8.23005808e-067, 1.10978743e-0

In [215]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [216]:
np.zeros((4, 4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [217]:
np.eye(44)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

- When constructing an array, you can specify the data type using a string

In [218]:
np.ones(10, dtype='float32')

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

## Basic array manipulations
- Attributes of arrays
    - Determining the size, shape, memory consumption, and data types of arrays


In [219]:
a1 = np.random.randint(10, size=10)  #one-dimensional array
a2 = np.random.randint(10, size=(10, 4)) # two-dimensional array
a3 = np.random.randint(10, size=(10, 3, 3)) # three-dimensional array

In [220]:
a2

array([[0, 5, 1, 6],
       [4, 3, 1, 9],
       [7, 9, 8, 0],
       [6, 6, 3, 5],
       [1, 0, 6, 6],
       [1, 4, 1, 0],
       [0, 3, 6, 4],
       [1, 3, 3, 2],
       [8, 7, 6, 8],
       [7, 0, 0, 3]])

In [221]:
a1.ndim

1

In [222]:
a1.shape

(10,)

In [223]:
a2.shape

(10, 4)

In [224]:
a3.dtype

dtype('int64')

In [225]:
a3.itemsize # the size (in bytes) of each array element

8

In [226]:
a3.nbytes # the total size (in bytes) of the array

720

#### Indexing and slicing arrays
- Getting and setting the value of individual array elements
- Getting and setting smaller subarrays within a larger array

In [227]:
arr = np.arange(0,10,1)

In [228]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [229]:
arr[5]

5

In [230]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [231]:
arr[2:5] =111 #data is not copied, and any modifications to the view will be reflected in the source array

In [232]:
arr

array([  0,   1, 111, 111, 111,   5,   6,   7,   8,   9])

In [233]:
lista= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [234]:
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [235]:
lista[2:5]

[2, 3, 4]

In [236]:
# lista[2:5]=111

In [237]:
lista[2:5]=[111,111,111]

In [238]:
lista

[0, 1, 111, 111, 111, 5, 6, 7, 8, 9]

In [239]:
array2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [240]:
array2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [241]:
array2D[2]

array([7, 8, 9])

In [242]:
array2D[1,1]

5

In [243]:
array2D[1,0]

4

In [244]:
array2D[1][0] = 44

In [245]:
array2D

array([[ 1,  2,  3],
       [44,  5,  6],
       [ 7,  8,  9]])

In [246]:
array2D[:, 0:1]

array([[ 1],
       [44],
       [ 7]])

In [247]:
array2D[2:,1:]

array([[8, 9]])

In [248]:
array2D[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

#### Boolean indexing

In [249]:
days = np.array(['Mon', "Tue", "Sat", "Sat", "Thu", "Fri", "Sat"])

In [250]:
days

array(['Mon', 'Tue', 'Sat', 'Sat', 'Thu', 'Fri', 'Sat'], dtype='<U3')

In [251]:
data = np.random.randn(7,5)

In [252]:
data

array([[ 1.24104532,  1.15099819,  0.88783875, -0.47458037, -0.05492844],
       [ 1.28155092,  0.75370079, -1.01671223, -0.33871227,  0.76009504],
       [-0.64830556, -0.03695793, -0.49720712,  0.98897816,  0.81977356],
       [-0.68223849,  0.66420403, -0.28552019,  0.88713925,  0.41992355],
       [ 0.17449746, -1.73467715, -0.61525216, -1.84519062,  0.32414482],
       [-0.20004645,  1.52878202,  1.3688318 , -2.20460869, -1.20723702],
       [ 1.17604836, -0.46544657,  1.26480182, -0.84737405, -0.0227624 ]])

In [253]:
data < 0

array([[False, False, False,  True,  True],
       [False, False,  True,  True, False],
       [ True,  True,  True, False, False],
       [ True, False,  True, False, False],
       [False,  True,  True,  True, False],
       [ True, False, False,  True,  True],
       [False,  True, False,  True,  True]])

In [254]:
data[data <0]=0

In [255]:
data

array([[1.24104532, 1.15099819, 0.88783875, 0.        , 0.        ],
       [1.28155092, 0.75370079, 0.        , 0.        , 0.76009504],
       [0.        , 0.        , 0.        , 0.98897816, 0.81977356],
       [0.        , 0.66420403, 0.        , 0.88713925, 0.41992355],
       [0.17449746, 0.        , 0.        , 0.        , 0.32414482],
       [0.        , 1.52878202, 1.3688318 , 0.        , 0.        ],
       [1.17604836, 0.        , 1.26480182, 0.        , 0.        ]])

In [256]:
array2D

array([[ 1,  2,  3],
       [44,  5,  6],
       [ 7,  8,  9]])

In [257]:
array2D == 5

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [258]:
array2D[array2D == 5]=0

In [259]:
array2D

array([[ 1,  2,  3],
       [44,  0,  6],
       [ 7,  8,  9]])

In [260]:
days == "Sat"

array([False, False,  True,  True, False, False,  True])

In [261]:
data

array([[1.24104532, 1.15099819, 0.88783875, 0.        , 0.        ],
       [1.28155092, 0.75370079, 0.        , 0.        , 0.76009504],
       [0.        , 0.        , 0.        , 0.98897816, 0.81977356],
       [0.        , 0.66420403, 0.        , 0.88713925, 0.41992355],
       [0.17449746, 0.        , 0.        , 0.        , 0.32414482],
       [0.        , 1.52878202, 1.3688318 , 0.        , 0.        ],
       [1.17604836, 0.        , 1.26480182, 0.        , 0.        ]])

In [262]:
len(days)

7

In [263]:
data.shape


(7, 5)

In [264]:
data[days == "Sat"]

array([[0.        , 0.        , 0.        , 0.98897816, 0.81977356],
       [0.        , 0.66420403, 0.        , 0.88713925, 0.41992355],
       [1.17604836, 0.        , 1.26480182, 0.        , 0.        ]])

In [265]:
data[days == "Mon"]

array([[1.24104532, 1.15099819, 0.88783875, 0.        , 0.        ]])

In [266]:
data[days != "Mon"]

array([[1.28155092, 0.75370079, 0.        , 0.        , 0.76009504],
       [0.        , 0.        , 0.        , 0.98897816, 0.81977356],
       [0.        , 0.66420403, 0.        , 0.88713925, 0.41992355],
       [0.17449746, 0.        , 0.        , 0.        , 0.32414482],
       [0.        , 1.52878202, 1.3688318 , 0.        , 0.        ],
       [1.17604836, 0.        , 1.26480182, 0.        , 0.        ]])

In [267]:
data[~(days == "Mon")]

array([[1.28155092, 0.75370079, 0.        , 0.        , 0.76009504],
       [0.        , 0.        , 0.        , 0.98897816, 0.81977356],
       [0.        , 0.66420403, 0.        , 0.88713925, 0.41992355],
       [0.17449746, 0.        , 0.        , 0.        , 0.32414482],
       [0.        , 1.52878202, 1.3688318 , 0.        , 0.        ],
       [1.17604836, 0.        , 1.26480182, 0.        , 0.        ]])

In [268]:
data[(days=="Mon") |(days=="Sat")]

array([[1.24104532, 1.15099819, 0.88783875, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.98897816, 0.81977356],
       [0.        , 0.66420403, 0.        , 0.88713925, 0.41992355],
       [1.17604836, 0.        , 1.26480182, 0.        , 0.        ]])

In [269]:
data[data<0]

array([], dtype=float64)

#### Fancy Indexing
- Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.
- To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order

In [270]:
arr = np.empty((10, 6))

In [271]:
for i in range(10):
    arr[i] = i

In [272]:
arr

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9.]])

In [273]:
arr[[2,1,4]]

array([[2., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4., 4.]])

In [274]:
arr[np.array([1,5,4,3,6,6,7])]

array([[1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3., 3.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7.]])

#### Reshaping of arrays
- Changing the shape of a given array


In [275]:
arr.shape

(10, 6)

In [276]:
arr

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9.]])

In [277]:
arr.reshape((-1,15))

array([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 2., 2., 2.],
       [2., 2., 2., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 6., 6., 6., 6., 6., 6., 7., 7., 7.],
       [7., 7., 7., 8., 8., 8., 8., 8., 8., 9., 9., 9., 9., 9., 9.]])

In [278]:
arr.reshape((30,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [4., 4.],
       [4., 4.],
       [4., 4.],
       [5., 5.],
       [5., 5.],
       [5., 5.],
       [6., 6.],
       [6., 6.],
       [6., 6.],
       [7., 7.],
       [7., 7.],
       [7., 7.],
       [8., 8.],
       [8., 8.],
       [8., 8.],
       [9., 9.],
       [9., 9.],
       [9., 9.]])

In [279]:
arr.reshape((3,2,10))

array([[[0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
        [1., 1., 2., 2., 2., 2., 2., 2., 3., 3.]],

       [[3., 3., 3., 3., 4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5., 6., 6., 6., 6.]],

       [[6., 6., 7., 7., 7., 7., 7., 7., 8., 8.],
        [8., 8., 8., 8., 9., 9., 9., 9., 9., 9.]]])

#### Change the data type of an array.

In [280]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)

In [281]:
y= x.astype(float)

In [282]:
y

array([[ 2.,  4.,  6.],
       [ 6.,  8., 10.]])

#### Joining and splitting of arrays
- Combining multiple arrays into one, and splitting one array into many
  - np.concatenate takes a tuple or list of arrays as its first argument

In [283]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

In [284]:
x

array([1, 2, 3, 4, 5])

In [285]:
y

array([ 6,  7,  8,  9, 10])

In [286]:
np.concatenate([x,y])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [287]:
x.ndim

1

In [288]:
x.shape

(5,)

In [289]:
# np.concatenate([x,y],axis=1)

In [290]:
xR=x.reshape(1,-1)
yR=y.reshape(1,-1)

In [291]:
xR

array([[1, 2, 3, 4, 5]])

In [292]:
xR.ndim

2

In [293]:
xR.shape

(1, 5)

In [294]:
np.concatenate([xR,yR],axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [295]:
np.concatenate([x,y,x,x,y,x,y,x,y,x,y])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  1,  2,
        3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10])

In [296]:
arrSmall = np.array([[1,2,3],[4,5,6]])

In [297]:
arrSmall

array([[1, 2, 3],
       [4, 5, 6]])

In [298]:
np.concatenate([arrSmall,arrSmall], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions
- The opposite of concatenation is splitting, which is implemented by the functions np.split


In [299]:
x = np.array([1,2,3])
y = np.array([[4,5,6],[7,8,9]])

In [300]:
x

array([1, 2, 3])

In [301]:
np.vstack([x,y])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [302]:
np.hstack([y,y])

array([[4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [303]:
x = np.hstack([x,x,x,x])

In [304]:
x

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [305]:
np.split(x,[3,6,7])

[array([1, 2, 3]), array([1, 2, 3]), array([1]), array([2, 3, 1, 2, 3])]

In [306]:
y

array([[4, 5, 6],
       [7, 8, 9]])

In [307]:
z,k = np.split(y,[2])

In [308]:
z

array([[4, 5, 6],
       [7, 8, 9]])

In [309]:
k

array([], shape=(0, 3), dtype=int64)

## Computation on NumPy Arrays: 



- Any arithmetic operations between equal-size arrays applies the operation elementwise
- Arithmetic operations with scalars are propagating the value to each element

In [310]:
arr1 = np.random.randint(10,size= (10,10))
arr2 = np.random.randint(10,size= (10,10))

In [311]:
arr1

array([[1, 7, 0, 3, 0, 6, 2, 6, 4, 7],
       [3, 4, 8, 8, 5, 1, 6, 5, 6, 3],
       [7, 3, 9, 2, 7, 9, 7, 0, 1, 7],
       [5, 8, 7, 5, 6, 5, 1, 2, 6, 0],
       [5, 6, 7, 8, 2, 8, 3, 3, 3, 7],
       [3, 2, 7, 7, 9, 8, 2, 2, 5, 8],
       [9, 7, 7, 6, 8, 8, 8, 6, 4, 0],
       [0, 0, 9, 2, 6, 4, 7, 5, 7, 1],
       [8, 6, 7, 5, 8, 6, 8, 2, 7, 4],
       [3, 7, 9, 6, 4, 9, 9, 6, 2, 1]])

In [312]:
arr1 * 125

array([[ 125,  875,    0,  375,    0,  750,  250,  750,  500,  875],
       [ 375,  500, 1000, 1000,  625,  125,  750,  625,  750,  375],
       [ 875,  375, 1125,  250,  875, 1125,  875,    0,  125,  875],
       [ 625, 1000,  875,  625,  750,  625,  125,  250,  750,    0],
       [ 625,  750,  875, 1000,  250, 1000,  375,  375,  375,  875],
       [ 375,  250,  875,  875, 1125, 1000,  250,  250,  625, 1000],
       [1125,  875,  875,  750, 1000, 1000, 1000,  750,  500,    0],
       [   0,    0, 1125,  250,  750,  500,  875,  625,  875,  125],
       [1000,  750,  875,  625, 1000,  750, 1000,  250,  875,  500],
       [ 375,  875, 1125,  750,  500, 1125, 1125,  750,  250,  125]])

In [313]:
arr1 + arr2

array([[ 2,  7,  2, 11,  0, 12,  9,  6,  6,  8],
       [ 6,  5, 12,  8, 10,  5, 15, 11,  7, 11],
       [14,  7, 18,  5,  9, 16, 13,  4,  3, 16],
       [ 6, 15, 14,  9,  6, 14,  6,  7,  9,  5],
       [12, 11, 13, 16,  4,  8, 11,  5,  9, 11],
       [ 3,  2, 10, 10,  9, 12, 11,  8,  5, 12],
       [ 9,  7,  7,  7, 16, 13, 13, 15, 12,  4],
       [ 9,  7, 11,  7, 15,  9,  7, 10, 12,  4],
       [11, 10,  9,  9, 16, 14, 15,  7, 11, 11],
       [12, 14, 12, 11, 10, 11, 14,  8,  5,  9]])

In [314]:
arr1 * arr2 - arr1 / ( arr2 +1)

array([[ 0.5       , -7.        ,  0.        , 23.66666667,  0.        ,
        35.14285714, 13.75      , -6.        ,  6.66666667,  3.5       ],
       [ 8.25      ,  2.        , 30.4       , -8.        , 24.16666667,
         3.8       , 53.4       , 29.28571429,  3.        , 23.66666667],
       [48.125     , 11.4       , 80.1       ,  5.5       , 11.66666667,
        61.875     , 41.        ,  0.        ,  1.66666667, 62.3       ],
       [ 2.5       , 55.        , 48.125     , 19.        , -6.        ,
        44.5       ,  4.83333333,  9.66666667, 16.5       ,  0.        ],
       [34.375     , 29.        , 41.        , 63.11111111,  3.33333333,
        -8.        , 23.66666667,  5.        , 17.57142857, 26.6       ],
       [-3.        , -2.        , 19.25      , 19.25      , -9.        ,
        30.4       , 17.8       , 11.71428571, -5.        , 30.4       ],
       [-9.        , -7.        , -7.        ,  3.        , 63.11111111,
        38.66666667, 38.66666667, 53.4       

- Transposing Arrays and inner matrix product

In [315]:
arr1

array([[1, 7, 0, 3, 0, 6, 2, 6, 4, 7],
       [3, 4, 8, 8, 5, 1, 6, 5, 6, 3],
       [7, 3, 9, 2, 7, 9, 7, 0, 1, 7],
       [5, 8, 7, 5, 6, 5, 1, 2, 6, 0],
       [5, 6, 7, 8, 2, 8, 3, 3, 3, 7],
       [3, 2, 7, 7, 9, 8, 2, 2, 5, 8],
       [9, 7, 7, 6, 8, 8, 8, 6, 4, 0],
       [0, 0, 9, 2, 6, 4, 7, 5, 7, 1],
       [8, 6, 7, 5, 8, 6, 8, 2, 7, 4],
       [3, 7, 9, 6, 4, 9, 9, 6, 2, 1]])

In [316]:
arr1.T

array([[1, 3, 7, 5, 5, 3, 9, 0, 8, 3],
       [7, 4, 3, 8, 6, 2, 7, 0, 6, 7],
       [0, 8, 9, 7, 7, 7, 7, 9, 7, 9],
       [3, 8, 2, 5, 8, 7, 6, 2, 5, 6],
       [0, 5, 7, 6, 2, 9, 8, 6, 8, 4],
       [6, 1, 9, 5, 8, 8, 8, 4, 6, 9],
       [2, 6, 7, 1, 3, 2, 8, 7, 8, 9],
       [6, 5, 0, 2, 3, 2, 6, 5, 2, 6],
       [4, 6, 1, 6, 3, 5, 4, 7, 7, 2],
       [7, 3, 7, 0, 7, 8, 0, 1, 4, 1]])

In [317]:
np.dot(arr1,arr1.T)

array([[200, 148, 155, 144, 204, 178, 192, 109, 185, 193],
       [148, 285, 234, 230, 249, 258, 309, 234, 302, 285],
       [155, 234, 372, 232, 291, 314, 347, 226, 348, 316],
       [144, 230, 232, 265, 241, 245, 312, 188, 294, 266],
       [204, 249, 291, 241, 318, 297, 318, 187, 308, 306],
       [178, 258, 314, 245, 297, 353, 316, 230, 327, 284],
       [192, 309, 347, 312, 318, 316, 459, 269, 409, 395],
       [109, 234, 226, 188, 187, 230, 269, 261, 264, 261],
       [185, 302, 348, 294, 308, 327, 409, 264, 407, 347],
       [193, 285, 316, 266, 306, 284, 395, 261, 347, 394]])

- Other operations


Algebric operations

```
+	np.add	Addition (e.g., 1 + 1 = 2)
-	np.subtract	Subtraction (e.g., 3 - 2 = 1)
-	np.negative	Unary negation (e.g., -2)
*	np.multiply	Multiplication (e.g., 2 * 3 = 6)
/	np.divide	Division (e.g., 3 / 2 = 1.5)
//	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
**	np.power	Exponentiation (e.g., 2 ** 3 = 8)
%	np.mod	Modulus/remainder (e.g., 9 % 4 = 1)
```

Trigonometric functions:

```
sin, cos, tan	compute sine, cosine and tangent of angles
arcsin, arccos, arctan	calculate inverse sine, cosine and tangent
hypot	calculate hypotenuse of given right triangle
sinh, cosh, tanh	compute hyperbolic sine, cosine and tangent
arcsinh, arccosh, arctanh	compute inverse hyperbolic sine, cosine and tangent
deg2rad	convert degree into radians
rad2deg	convert radians into degree
```

Statistical functions:

```
amin, amax	returns minimum or maximum of an array or along an axis
ptp	returns range of values (maximum-minimum) of an array or along an axis
percentile(a, p, axis)	calculate pth percentile of array or along specified axis
median	compute median of data along specified axis
mean	compute mean of data along specified axis
std	compute standard deviation of data along specified axis
var	compute variance of data along specified axis
average	compute average of data along specified axis
```

In [318]:
arr1

array([[1, 7, 0, 3, 0, 6, 2, 6, 4, 7],
       [3, 4, 8, 8, 5, 1, 6, 5, 6, 3],
       [7, 3, 9, 2, 7, 9, 7, 0, 1, 7],
       [5, 8, 7, 5, 6, 5, 1, 2, 6, 0],
       [5, 6, 7, 8, 2, 8, 3, 3, 3, 7],
       [3, 2, 7, 7, 9, 8, 2, 2, 5, 8],
       [9, 7, 7, 6, 8, 8, 8, 6, 4, 0],
       [0, 0, 9, 2, 6, 4, 7, 5, 7, 1],
       [8, 6, 7, 5, 8, 6, 8, 2, 7, 4],
       [3, 7, 9, 6, 4, 9, 9, 6, 2, 1]])

In [319]:
np.median(arr1)

6.0

In [320]:
np.add(arr1,arr2) #subtract, multiply, divide

array([[ 2,  7,  2, 11,  0, 12,  9,  6,  6,  8],
       [ 6,  5, 12,  8, 10,  5, 15, 11,  7, 11],
       [14,  7, 18,  5,  9, 16, 13,  4,  3, 16],
       [ 6, 15, 14,  9,  6, 14,  6,  7,  9,  5],
       [12, 11, 13, 16,  4,  8, 11,  5,  9, 11],
       [ 3,  2, 10, 10,  9, 12, 11,  8,  5, 12],
       [ 9,  7,  7,  7, 16, 13, 13, 15, 12,  4],
       [ 9,  7, 11,  7, 15,  9,  7, 10, 12,  4],
       [11, 10,  9,  9, 16, 14, 15,  7, 11, 11],
       [12, 14, 12, 11, 10, 11, 14,  8,  5,  9]])

In [321]:
arr1+arr2

array([[ 2,  7,  2, 11,  0, 12,  9,  6,  6,  8],
       [ 6,  5, 12,  8, 10,  5, 15, 11,  7, 11],
       [14,  7, 18,  5,  9, 16, 13,  4,  3, 16],
       [ 6, 15, 14,  9,  6, 14,  6,  7,  9,  5],
       [12, 11, 13, 16,  4,  8, 11,  5,  9, 11],
       [ 3,  2, 10, 10,  9, 12, 11,  8,  5, 12],
       [ 9,  7,  7,  7, 16, 13, 13, 15, 12,  4],
       [ 9,  7, 11,  7, 15,  9,  7, 10, 12,  4],
       [11, 10,  9,  9, 16, 14, 15,  7, 11, 11],
       [12, 14, 12, 11, 10, 11, 14,  8,  5,  9]])

In [322]:
np.sqrt(arr2)

array([[1.        , 0.        , 1.41421356, 2.82842712, 0.        ,
        2.44948974, 2.64575131, 0.        , 1.41421356, 1.        ],
       [1.73205081, 1.        , 2.        , 0.        , 2.23606798,
        2.        , 3.        , 2.44948974, 1.        , 2.82842712],
       [2.64575131, 2.        , 3.        , 1.73205081, 1.41421356,
        2.64575131, 2.44948974, 2.        , 1.41421356, 3.        ],
       [1.        , 2.64575131, 2.64575131, 2.        , 0.        ,
        3.        , 2.23606798, 2.23606798, 1.73205081, 2.23606798],
       [2.64575131, 2.23606798, 2.44948974, 2.82842712, 1.41421356,
        0.        , 2.82842712, 1.41421356, 2.44948974, 2.        ],
       [0.        , 0.        , 1.73205081, 1.73205081, 0.        ,
        2.        , 3.        , 2.44948974, 0.        , 2.        ],
       [0.        , 0.        , 0.        , 1.        , 2.82842712,
        2.23606798, 2.23606798, 3.        , 2.82842712, 2.        ],
       [3.        , 2.64575131, 1.4142135

In [323]:
np.max(arr1)

9

In [324]:
arr1

array([[1, 7, 0, 3, 0, 6, 2, 6, 4, 7],
       [3, 4, 8, 8, 5, 1, 6, 5, 6, 3],
       [7, 3, 9, 2, 7, 9, 7, 0, 1, 7],
       [5, 8, 7, 5, 6, 5, 1, 2, 6, 0],
       [5, 6, 7, 8, 2, 8, 3, 3, 3, 7],
       [3, 2, 7, 7, 9, 8, 2, 2, 5, 8],
       [9, 7, 7, 6, 8, 8, 8, 6, 4, 0],
       [0, 0, 9, 2, 6, 4, 7, 5, 7, 1],
       [8, 6, 7, 5, 8, 6, 8, 2, 7, 4],
       [3, 7, 9, 6, 4, 9, 9, 6, 2, 1]])

In [325]:
arr2

array([[1, 0, 2, 8, 0, 6, 7, 0, 2, 1],
       [3, 1, 4, 0, 5, 4, 9, 6, 1, 8],
       [7, 4, 9, 3, 2, 7, 6, 4, 2, 9],
       [1, 7, 7, 4, 0, 9, 5, 5, 3, 5],
       [7, 5, 6, 8, 2, 0, 8, 2, 6, 4],
       [0, 0, 3, 3, 0, 4, 9, 6, 0, 4],
       [0, 0, 0, 1, 8, 5, 5, 9, 8, 4],
       [9, 7, 2, 5, 9, 5, 0, 5, 5, 3],
       [3, 4, 2, 4, 8, 8, 7, 5, 4, 7],
       [9, 7, 3, 5, 6, 2, 5, 2, 3, 8]])

In [326]:
np.maximum(arr1, arr2)

array([[1, 7, 2, 8, 0, 6, 7, 6, 4, 7],
       [3, 4, 8, 8, 5, 4, 9, 6, 6, 8],
       [7, 4, 9, 3, 7, 9, 7, 4, 2, 9],
       [5, 8, 7, 5, 6, 9, 5, 5, 6, 5],
       [7, 6, 7, 8, 2, 8, 8, 3, 6, 7],
       [3, 2, 7, 7, 9, 8, 9, 6, 5, 8],
       [9, 7, 7, 6, 8, 8, 8, 9, 8, 4],
       [9, 7, 9, 5, 9, 5, 7, 5, 7, 3],
       [8, 6, 7, 5, 8, 8, 8, 5, 7, 7],
       [9, 7, 9, 6, 6, 9, 9, 6, 3, 8]])

- np.where 
    - Return elements chosen from x or y depending on condition.

In [327]:
a = np.arange(10)

In [328]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [329]:
np.where(a>5,0,10)

array([10, 10, 10, 10, 10, 10,  0,  0,  0,  0])

In [330]:
b = np.arange(10,20)

In [331]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [332]:
np.where(a%2==1,a,b)

array([10,  1, 12,  3, 14,  5, 16,  7, 18,  9])

### Mathematical and Statistical Methods

- A set of mathematical functions which compute statistics about an entire array or about the data along an axis are accessible as array methods. 


In [333]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [334]:
a.mean()

4.5

In [335]:
a.sum()

45

In [336]:
a.std()

2.8722813232690143

In [337]:
a.var()

8.25

In [338]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [339]:
b.cumprod()

array([          10,          110,         1320,        17160,
             240240,      3603600,     57657600,    980179200,
        17643225600, 335221286400])

## Boolean Arrays

- Boolean values are coerced to 1 (True) and 0 (False) in the above methods. 
- Sum is often used as a means of counting True values in a boolean array


In [340]:
boola = np.random.randint(2, size=100)

In [341]:
boola

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [342]:
boola.sum()

39

In [343]:
bools = np.array([True,True,False,False, True])

In [344]:
bools.sum()

3

In [345]:
bools.any()

True

In [346]:
bools.all()

False

In [347]:
bools[:2].all()

True

## Sorting
- Like Python’s built-in list type, NumPy arrays can be sorted in-place using the sort method

In [348]:
boola.sort()

In [349]:
boola

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [350]:
arrsort =np.random.randn(4,3)

In [351]:
arrsort

array([[-1.82549359,  0.4839276 ,  1.26387638],
       [ 1.1300931 , -0.55800692, -0.01122   ],
       [-0.20072752, -1.72256221, -0.87840382],
       [ 0.9770532 ,  0.03477518,  0.52731587]])

In [352]:
arrsort.sort(0)

In [353]:
arrsort

array([[-1.82549359, -1.72256221, -0.87840382],
       [-0.20072752, -0.55800692, -0.01122   ],
       [ 0.9770532 ,  0.03477518,  0.52731587],
       [ 1.1300931 ,  0.4839276 ,  1.26387638]])

In [354]:
arrsort.sort(1)

In [355]:
arrsort

array([[-1.82549359, -1.72256221, -0.87840382],
       [-0.55800692, -0.20072752, -0.01122   ],
       [ 0.03477518,  0.52731587,  0.9770532 ],
       [ 0.4839276 ,  1.1300931 ,  1.26387638]])

### Unique and Other Set Logic

- NumPy has some basic set operations for one-dimensional ndarrays.

In [356]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [357]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')