# Python Informal Introduction

# Foundamentals
1. Official Python tutorial (http://docs.python.org)
2. Python is an interpreted language. 
    - The Python interpreter runs a program by executing one statement at a time.
3. Indentation
4. Statements also do not need to be terminated by semicolons

### Python is an object-oriented programming language 
- Everything is an object
  - An object is a collection of data, commonly known as **attributes**, and the object has certain predefined **functions** to update these data or exchange data with other objects.
- Every number, string, data structure, function, class, module, ... exists in the Python interpreter in its own “box” which is referred to as Python object. 
- Each object has an associated type (for example, string or function) and internal data. 
-In practice this makes the language very flexible, as even functions can be treated just like any other object.



In [288]:
%%script python --no-raise-error


UsageError: %%script is a cell magic, but the cell body is empty.


In [289]:
type(5)

int

In [290]:
type("Francesco")

str

Comments:
  - Any text preceded by the hash mark (#) is ignored by the Python interpreter
  - _# This code will no be executed_

In [291]:
# This is a comment, then it is ignored

### Using Python as a Calculator

In [292]:
5*6

30

In [293]:
50//4

12

In [294]:
50/2

25.0

In [295]:
type(50//2)

int

Division (/) always returns a float. To do floor division and get an integer result (discarding any fractional result) you can use the // operator; to calculate the remainder you can use %.



In [296]:
# Statement
a = 1 + 2
a

3

In [297]:
print(a)

3


In [298]:
a=a+4

In [299]:
a1 = a

In [300]:
print(a)

7


In [301]:
type(a)

int

The last printed expression is assigned to the variable _. 
It is somewhat easier to continue calculations

In [302]:
tax = 12.5 / 100
price = 100.50
price * tax


12.5625

In [303]:
price

100.5

In [304]:
a = 7; b=7

In [305]:
a=7
b=7

### Function and object method calls

- Functions are called using parentheses and passing zero or more arguments, optionally assigning the returned value to a variable.
- The list if built-in Python functions is https://docs.python.org/3/library/functions.html

In [306]:
# max returns the largest item in an iterable
max(1, 2, 3)

3

In [307]:
result = max(1,5)
result

5

In [308]:
# len returns the length of an object
len([1, 2, 4])

3

In [309]:
# print a message onto the screen
print("Luigi")

Luigi


- In Python a function is defined using the _**def**_ keyword

In [310]:
def somma(a, b):
  c = a + b
  #print("Somma")
  return c

In [311]:
somma(8, 9)

17

In [312]:
#somma(8)
a= somma(7, 6)

In [313]:
type(a)

int

In [314]:
a= somma(1.3, 5)

In [315]:
type(a)

float

In [316]:
somma(1,10.)

11.0

In [317]:
#somma('ciao ', 15)

In [318]:
somma('ciao ', str(15))

'ciao 15'

In [319]:
def somma(a=5, b=7):
    return a + b

In [320]:
somma(12)

19

In [321]:
somma(b=100, a=4)

104

In [322]:
somma(4,b=100)

104

In [323]:
somma()

12

In [324]:
#Functions can return more values
def sumComplete(a=5, b=7):
    return a,b,a + b

In [325]:
sumComplete()

(5, 7, 12)

In [326]:
(add1, add2, sum) = sumComplete(3,4)

In [327]:
sum

7

- Almost every object in Python has methods, that have access to the object’s internal contents. 
They can be called using the syntax:
    - _obj.method(1, 2, 3)_
- Functions can take both positional and keyword arguments:
    - _result = f(a, b, c, d=5, e="fff")_

- Variables and pass-by-reference
    - When assigning a variable in Python, you are creating a reference to an object.
    - Assignment is also referred to as binding, as we are binding a name to an object. 
    - When you pass objects as arguments to a function, you are only passing references; no copying occurs

In [328]:
a = [1, 2, 3]

In [329]:
a

[1, 2, 3]

In [330]:
b = a

In [331]:
b

[1, 2, 3]

In [332]:
a.append(4)

In [333]:
a

[1, 2, 3, 4]

In [334]:
b

[1, 2, 3, 4]

In [335]:
a = 5
b = a

In [336]:
b

5

In [337]:
a = 6

In [338]:
b

5

### Dynamic references, strong types
- Object references in Python have no type associated with them
- The object to which a reference is bound at a given time does have a type
- Any given reference may be bound to objects of different types during the execution of a program

In [339]:
a = 7
f = "Francesco"
g= f

In [340]:
type(a)

int

In [341]:
type(f)

str

In [342]:
type(g)

str

In [343]:
result = 5.0

In [344]:
result + result

10.0

In [345]:
type(result)

float

In [346]:
result = "result"

In [347]:
type(result)

str

- Python is considered a strongly-typed language, 
    - every object has a specific type
    - implicit conversions occur only in certain obvious circumstances

In [348]:
a = 4
b = 2

In [349]:
type(a / b) # Note in Python 2.X this is integer

float

In [350]:
a / b

2.0

In [351]:
int(a / b)

2

In [352]:
type(a)

int

In [353]:
isinstance(a, int)

True

### Operators and comparison
- +,  -, \*,  /,  \*\*, ...
- The operators <, >, ==, >=, <=, and != compare the values of two objects

In [354]:
# Addition
21 + 11.4

32.4

In [355]:
# Difference
9 - 11

-2

In [356]:
# Multiplication
2 * 3

6

In [357]:
# Division
9 / 3

3.0

In [358]:
# Power
2 ** 3

8

In [359]:
5 != 4

True

In [360]:
5 == 4

False

In [361]:
5 > 4

True

In [362]:
5 < 4

False

In [363]:
4 >= 4

True

In [364]:
19 / 3

6.333333333333333

In [365]:
int(19 / 3)

6

In [366]:
19 // 3

6

In [367]:
19 % 3

1

### Imports
- In Python a module is simply a .py file containing function and variable definitions along with such things imported from other .py files. 

In [368]:
import numpy

In [369]:
numpy.array([1,2,3])

array([1, 2, 3])

In [370]:
type(numpy.array([1,2,3]))

numpy.ndarray

In [371]:
import numpy as np 

array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [372]:
from numpy import array
array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

## Mutable and immutable objects
- Most objects in Python are mutable: the object or values that they contain can be modified
  - lists, dicts, NumPy arrays, or most user-defined types (classes).
- Other object cannot be modified after their creation
  - strings and tuples.

In [373]:
a = 7

In [374]:
a = a + 1
a

8

In [375]:
esempio_Lista = [1, "Ciao", 4]

In [376]:
type(esempio_Lista)

list

In [377]:
esempio_Lista

[1, 'Ciao', 4]

In [378]:
esempio_Lista[2]

4

In [379]:
esempio_Lista[2] = 48


In [380]:
esempio_Lista

[1, 'Ciao', 48]

In [381]:
esempio_Stringa = "Francesco"

In [382]:
esempio_Stringa[8]

'o'

In [383]:
esempio_Stringa[8] = 'a'

TypeError: 'str' object does not support item assignment

In [ ]:
esempio_Stringa = 'Francesca'

## Scalar Types



### Numeric

- The primary Python types for numbers are int and float
   - In Python3, value of an integer is not restricted by the number of bits and can expand to the limit of the available memorys.

- Floating point numbers are represented with the float type.
   - Under the hood each one is a double-precision (64 bits) value.
   - They can also be expressed using scientific notation.


In [ ]:
intValue = 9223
intValue

In [ ]:
print(intValue**intValue)

In [ ]:
type(intValue)


In [ ]:
intValue = intValue +2

In [ ]:
intValue

In [ ]:
type(intValue)

In [ ]:
flVaue = 4.765

In [ ]:
flValueScient = 4.123e22

In [ ]:
flValueScient

In [ ]:
flValueScient + 1

In [ ]:
4.123 * 10**22

In [ ]:
type(flValueScient)

In [ ]:
#overflow
flValueScient**flValueScient

### Strings
- You can write string using either single quotes ' or double quotes "
- For multiline strings with line breaks, you can use triple quotes, either ''' or """
- Python strings are immutable; you cannot modify a string without creating a new string

In [ ]:
string1 = 'Questa è una stringa'
string1

In [ ]:
string2 = "Questa è una stringa"
string2

In [ ]:
string1 == string2

In [ ]:
string1 = 'Questa è una stringa'
stringLunga = '''
Stringa
su più
righe'''
stringLunga

In [ ]:
stringLunga

In [ ]:
type(string1)

In [ ]:
s = 'c'
type(s)

In [ ]:
len(string1)

- Many Python objects can be converted to a string using the str function    
- Adding two strings together concatenates them and produces a new string

In [ ]:
a = 42

In [ ]:
type(a)

In [ ]:
str(42)

In [ ]:
print(a)

In [ ]:
print(str(a))

In [ ]:
str(a)

In [ ]:
42 + 42

In [ ]:
'ciao' + 'ciao'

In [ ]:
b = 'Il risultato è '

In [ ]:
b + a

In [ ]:
b + str(a)

In [ ]:
int(7.12)

In [ ]:
int('ciao')

In [ ]:
int('10')

### Booleans
- The two boolean values are written as True and False. 
- Boolean values are combined with the and and or keywords

In [ ]:
b = True
b

In [ ]:
type(b)

In [ ]:
True or True

In [ ]:
True or False

### None
- None is the Python null value type
- If a function does not explicitly return a value, it implicitly returns None


In [ ]:
k = None 

In [ ]:
k is None

In [ ]:
not k is None

In [ ]:
type(k)

In [ ]:
def prova(a=1,b=1):
  c=a+b

In [ ]:
type(prova)

In [ ]:
result = prova()

In [ ]:
type(result)

### Dates and times
- The built-in Python datetime module provides datetime, date, and time types.


In [ ]:
import datetime
dt = datetime.datetime(2021, 6, 19)

In [ ]:
type(dt)

In [ ]:
dt.date()

In [ ]:
dt.time()

In [ ]:
dt.hour

In [ ]:
dt = datetime.datetime(2019, 7, 1, 23, 24)

In [ ]:
dt.time()

In [ ]:
dt.hour

In [ ]:
dt.minute

In [ ]:
today = datetime.date.today() 

In [ ]:
print(today)

In [ ]:
type(today)

In [ ]:
datetime.datetime.now()

## Control flow


### ***if***, ***elif***, and ***else***

In [ ]:
a = 4
b = 5

if (a < 5):
    print("minore")
else:
    print("a è maggiore o uguale")

if (b == 5):
    print("b uguale")
else: 
    print("b diverso")

In [ ]:
a = 5
if a == 7:
  print('7')
elif a == 5:
  print('5')
else:
  print('diverso da 5 e 7')

### ***for*** loops
    - for loops are for iterating over a collection (like a list or tuple) or an iterator

In [ ]:
sequence = [1, 2, 3, 5, 6]
for i in sequence:
    print("i = ", i)
    i = i + 1
    print("i+1 = ", i)
    

In [ ]:
sequence = [1, 2, None, 5, None, "francesco"]
for i in sequence:
    print(i)
    if i is None:
      print('errore')

In [ ]:
range(10)

In [ ]:
for i in range(10):
    print(i)
    

In [ ]:
range(1, 10)

In [ ]:
for i in range(1, 10):
  print(i)

In [ ]:
a = range(0,10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for i in a:
  print(i)

In [ ]:
print(a)

In [ ]:
a[4]

In [ ]:
for i in range(10):
    print(i)

In [ ]:
for i in range(1, 10, 2):
    print(i)

In [ ]:
for i in range(10, 22, 3):
  print(i)

### ***while*** loops
    - A while loop specifies a condition and a block of code that is to be executed until the condition evaluates to False or the loop is explicitly ended with break


In [ ]:
while cond:
  # esegui il codice

In [ ]:
i = 0
while i < 10:
    print("i=",i)
    for a in range(i, 10):
      print ("a=",a )
      
    i = i + 1
    
    if i == 2:
      break

In [ ]:
do {
    codice
} while(cond)

In [ ]:
codice
while cond:
  codice

## Built-in Data Structures

### Tuple
- A tuple is a one-dimensional, fixed-length, immutable sequence of Python objects.

In [ ]:
tup = (1, 2, 3, 4, 5, 6)

In [ ]:
tup

In [ ]:
type(tup)

In [ ]:
tup

In [ ]:
tup[3]

In [ ]:
tup[3] = 1

In [ ]:
tup = (1, 2, 3, 1, 5, 6)
tup

In [ ]:
nestedTuple = (1, 3, 5, 7, 9), (2, 4, 6, 8, 10)

In [ ]:
nestedTuple

In [ ]:
nestedTuple[0]

In [ ]:
nestedTuple[0][0]

In [ ]:
nestedTuple[1][1]

In [ ]:
nestedTuple[0][4]

In [ ]:
nestedTuple = ((1, 3, 5, 7, 9), (2, 4, 6, 8, 10))
nestedTuple[1][1]

In [ ]:
nestedTuple

In [ ]:
nestedTuple[0][1]

In [ ]:
tuple("Francesco")

In [ ]:
tuple("Francesco")[0]

In [ ]:
tupMixed = 1, 'a', [1,2]

In [ ]:
tupMixed

In [ ]:
tupMixed[0]

In [ ]:
tupMixed[0] = 14

In [ ]:
tupMixed[2]

In [ ]:
tupMixed[2].append(14)

In [ ]:
tupMixed

-  Tuple methods 
    - Tuples can be concatenated using the + operator
    - One particularly useful method (also available on lists) is count, which counts the number of occurrences of a value  

In [ ]:
tupMixed

In [ ]:
nestedTuple + tupMixed

In [ ]:
t1 = (1, 2, 3)
t2 = (4, 5, 6)
t = t1 + t2
t

In [ ]:
tupMixed.count(1)

In [ ]:
tupMixed

In [ ]:
tupMixed.count('g')

In [ ]:
len(tupMixed)

### List

  - lists are variable-length and their contents can be modified
  - They can be defined using square brackets **\[ \]** or using the list type function

In [ ]:
listA = [0, 1, 2, 3]

In [ ]:
listA

In [ ]:
listA[0]

In [ ]:
listA[0] = 555

In [ ]:
listA

In [ ]:
listB = listA
listB

In [ ]:
listA[0]=1
listB

In [ ]:
listB[0]=44

In [ ]:
listA[1]=111

In [ ]:
tupMixed=(1,'a',[1,2,14])

In [ ]:
listB = list(tupMixed)

In [ ]:
listB


In [ ]:
listB[0] = 13

In [ ]:
listB

In [ ]:
list('abcd')

In [ ]:
for i in list('abcde'):
  print(i)

- List methods
    - Adding and removing elements
    - Concatenating and combining lists
    - Sorting
    - Slicing
    - Searching an element
    - Enumerating elements
    - Pairing lists



In [ ]:
listA

In [ ]:
# Adding element via append
listA.append(4)
listA

In [ ]:
listA.append(1000)
listA

In [ ]:
# Inserting an element in a specific location
listA.insert(1, "Francesco")
listA

In [ ]:
listA[1]

In [ ]:
listA

In [ ]:
# Removing an element from a specific location
listA.pop(0)

In [ ]:
listA

In [ ]:
# Removing a specific element (the first in case of duplication) from a list
listA.remove(4)

In [ ]:
listA

In [ ]:
listA.remove(4)

In [ ]:
if 4 in listA:
  listA.remove(4)

In [ ]:
# Concatenating
listA + listA

In [ ]:
listA

In [ ]:
# Extending
listA.extend([4,5])

In [ ]:
listA

In [ ]:
listA.append([4,5])

In [ ]:
listA

In [ ]:
# Sorting
listNum = [0,43,27,18,90,4]

In [ ]:
listNum.sort()

In [ ]:
listNum

In [ ]:
# Slicing
# You can select sections of list-like types (arrays, tuples, NumPy arrays) by using slice notation, 
# which in its basic form consists of start:stop passed to the indexing operator []
listNum

In [ ]:
listNum

In [ ]:
listNum[1]

In [ ]:
listNum[0:100]

In [ ]:
listNum[0:2]

In [ ]:
listNum[5]

In [ ]:
listNum[1:4]

In [ ]:
listNum[0:2]

In [ ]:
listNum[1:]

In [ ]:
listNum[:2]

In [ ]:
listNum

In [ ]:
listNum[-2]

In [ ]:
listNum[:3]

In [ ]:
listNum[-3:]

In [ ]:
listNum

In [ ]:
listNum[0:4:2]

In [ ]:
listNum[::-1]

In [ ]:
listNum[::-1]

In [ ]:
# Searching in List
2 in listNum

In [ ]:
4 in listNum

In [ ]:
# Python has a built-in function, enumerate, which returns a
# sequence of (i, value) tuples:

# for i, value in enumerate(collection):
#   do something with value

a = ["a", "b", "c", "d"]
for i, value in enumerate(a):
    print(str(i) + "   " + value)

In [ ]:
for i,z in enumerate(a):
  print(z)

In [ ]:
a = ["a", "b", "c", "d"]

In [ ]:
for ix, x in enumerate(a):
  print(ix, x)

In [ ]:
a

In [ ]:
# zip “pairs” up the elements of a number of lists, tuples, or other sequences to create a list of tuples
b = [1, 2, 3, 4]
zip(a, b)
list(zip(a, b))

In [ ]:
for x in zip(a, b):
  print(type(x))

### Dictionary
- It is hash map or associative array. 
- It is a flexibly-sized collection of key-value pairs, key and value are objects. 
- One way to create one is by using curly braces {} and using colons to separate keys and values

In [ ]:
diz = {}
diz['Firstname'] = 'francesco'
diz['Lastname'] = 'rossi'

In [ ]:
diz

In [ ]:
diz.keys()

In [ ]:
for i in diz.values():
  print(i)

In [ ]:
diz.items()

In [ ]:
del diz['Firstname']

In [ ]:
diz['parola'] = 0

In [ ]:
diz['parola'] += 1

In [ ]:
diz

In [ ]:
diz[0]=4

In [ ]:
diz

In [ ]:
d = {'Nome': 'Francesco', 4 : 48, 'cognome': 'Guerra'}
d

In [ ]:
d[4]

In [ ]:
d['job']

In [ ]:
d['job'] = 'PO'
d

- Creating dicts from sequences

In [ ]:
seqA = ['a', 'b', 'c', 'd', 'e']
seqB = range(1, 6)

mapping = {}
for key, value in zip(seqA, seqB):
  #print(key)
  #print(value)
  mapping[key] = value



In [ ]:
mapping

- Dictionary Methods
    - Searching for an element
    - Removing an element
    - keys and values

In [ ]:
dictTel = {"Francesco": 335666, "Matteo": 3478888, "Michela": 5454455}

In [ ]:
dictTel["Francesco"] = 666335

In [ ]:
dictTel

In [ ]:
if 'Matteo' in dictTel:
    print(dictTel['Matteo'])

In [ ]:
# Removing elements
dictTel.pop('Matteo')
dictTel

In [ ]:
dictTel.pop('Matteo')

In [ ]:
del dictTel["Michela"]
dictTel

In [ ]:
del dictTel["Michela"]

In [ ]:
dictTel

In [ ]:
# List of keys
dictTel.keys()

In [ ]:
# List of values
dictTel.values()

In [ ]:
if "Michela" in dictTel.keys():
  del dictTel["Michela"]

In [ ]:
dictTel.items()

In [ ]:
dictTel

In [ ]:
for k, val in dictTel.items():
  print(k)
  print(val)

### Set
- A set is an unordered collection of unique elements.  
- A set can be created in two ways: via the set function or using a set literal with curly braces



In [ ]:
listSet = [1, 1, 1, 1, 1, 1, 2, 3, 4]
listSet 

In [ ]:
set(listSet)

In [ ]:
setExample = {1, 1, 1, 1, 1, 1, 2, 3, 4}

In [ ]:
setExample

In [ ]:
setExample.intersection({2, 3, 4, 5})

In [ ]:
setExample.union({2, 3, 4, 5})

## List, Set, and Dict Comprehensions
- List comprehensions are one of the most-loved Python language features. 
- They allow you to concisely form a new list by filtering the elements of a collection and transforming the elements passing the filter in one concise expression. They take the basic form:
- [expr **for** val **in** collection **if** condition]

In [ ]:
'se'.upper()

In [ ]:
new = []
listMin = ['una', 'lista', 'di', 'parole', 'minuscole', 'e', 'MAIUSCOLE']

for x in listMin:
  if len(x) > 2:
    x = x.upper()
    new.append(x)

In [ ]:
new

In [ ]:
[x.upper() for x in listMin if len(x)>2]

In [ ]:
{str(i):i for i in [1,2,3,4,5]}

In [ ]:
fruits = ['apple', 'mango', 'banana','cherry']
{f:len(f) for f in fruits}

In [ ]:
for i,j in enumerate(fruits):
  print(i)
  print(j)

In [ ]:
{f:i for i,f in enumerate(fruits)}

## Anonymous (Lambda) Functions

- Python has support for so-called anonymous or lambda functions
    - a way of writing functions consisting of a single statement
    - the result is the return value. 
    - they are defined with the lambda keyword

In [ ]:
def twoTimes(x):
    return x * 2

In [ ]:
twoTimes(3)

In [ ]:
twoTimesLambda = lambda x: x * 2

In [ ]:
twoTimesLambda(22)

In [ ]:
def applyList(aList, aFunction):
    return [aFunction(x) for x in aList]

In [ ]:
applyList([1, 4, 5, 7, 11], twoTimes)

In [ ]:
applyList([2, 4, 5, 7, 9], lambda x: x ** 2)